export const VENDOR_EXT_KEYS = [
  'x-error-message',
  'x-required-message',
  'x-const-message',
  'x-enum-message',
  'x-minimum-message',
  'x-maximum-message',
  'x-exclusiveMinimum-message',
  'x-exclusiveMaximum-message',
  'x-multipleOf-message',
  'x-minLength-message',
  'x-maxLength-message',
  'x-pattern-message',
  'x-length-message',
  'x-minItems-message',
  'x-maxItems-message',
  'x-uniqueItems-message',
  'x-contains-message',
  'x-minContains-message',
  'x-maxContains-message',
  'x-prefixItems-message',
  'x-items-message',
  'x-minProperties-message',
  'x-maxProperties-message',
  'x-additionalProperties-message',
  'x-propertyNames-message',
  'x-patternProperties-message',
  'x-dependentRequired-message',
  'x-dependentSchemas-message',
  'x-properties-message',
  'x-unevaluatedProperties-message',
  'x-unevaluatedItems-message',
  'x-if-message',
  'x-then-message',
  'x-else-message',
  'x-allOf-message',
  'x-anyOf-message',
  'x-oneOf-message',
  'x-not-message',
  'x-implication-message',
  'x-brand',
] as const

export type VendorExtensions = {
  readonly [K in (typeof VENDOR_EXT_KEYS)[number]]?: string
}
